name: Daily Commit

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make change
        run: |
          echo "$(date)" >> log.txt

      - name: Commit and push
        run: |
          git config --global user.name "Devansh-04"
          git config --global user.email "devansh@example.com"
          git add .
          git commit -m "Daily commit" || exit 0
          git push
