name: Daily Commit

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make change
        run: date >> log.txt
